export enum ControlTypes {
  TextInput ="text", 
  PasswordInput ="password",
  Url="url",  
  Hidden="hidden",  
  NumberInput="number", 
  Selection="select", 
  MultiSelection="multi-select",
  CheckBox="checkbox", 
  DatePicker="date-picker", 
  LocalFilePicker="local-file-picker", 
  TextArea="textarea", 
  RichTextEditor="rich-edit", 
  MapPicker="map-picker", 
  TableBuilder="table-builder",
}