 name: 'Build and deploy ASP.NET Core with Angular to Azure Web App: a204-lab2-webapp'
 on: 
  push: 
   branches: 
    - main
 env:
  REMORE_PUBLISH_PATH: /

 jobs:
   build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
              
      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install Yarn
        run: |
             npm install -g yarn
           
      - name: Install Angular CLI with Yarn
        run: |
              cd Presentation/BackPanel.WebApplication/ClientApp
              yarn install
              yarn global add @angular/cli
  
      - name: Build .NET Core
        run: |
          dotnet publish -c Release --output publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with: 
          app-name: 'a204-lab2-webapp'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_33a25860435941b1ab6a70fe622afb3b }}
          package: publish
    
    
    
     
       
